# Generated by Django 5.2.3 on 2025-09-03 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actiondisciplinaire',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affectation',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affectation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='hr_payroll.agent'),
        ),
        migrations.AddField(
            model_name='actiondisciplinaire',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_disciplinaires', to='hr_payroll.agent'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='hr_payroll.agent'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='calcule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agent',
            name='bureau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='hr_payroll.bureau'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='bureau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='hr_payroll.bureau'),
        ),
        migrations.AddField(
            model_name='competenceagent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='hr_payroll.agent'),
        ),
        migrations.AddField(
            model_name='competenceagent',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents_competents', to='hr_payroll.competence'),
        ),
        migrations.AddField(
            model_name='competenceagent',
            name='evalue_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competences_evaluees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotations', to='hr_payroll.agent'),
        ),
        migrations.AddField(
            model_name='cotation',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotations_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotation',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotations_validees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bureau',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='hr_payroll.direction'),
        ),
        migrations.AddField(
            model_name='agent',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='hr_payroll.grade'),
        ),
        migrations.AddField(
            model_name='grillesalariale',
            name='element_paie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles_salariales', to='hr_payroll.elementpaie'),
        ),
        migrations.AddField(
            model_name='grillesalariale',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles_salariales', to='hr_payroll.grade'),
        ),
        migrations.AddField(
            model_name='historiquepaie',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_paie', to='hr_payroll.agent'),
        ),
        migrations.AddField(
            model_name='historiquepaie',
            name='archive_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquepaie',
            name='bulletin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='hr_payroll.bulletinpaie'),
        ),
        migrations.AddField(
            model_name='mouvementpaie',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_paie', to='hr_payroll.agent'),
        ),
        migrations.AddField(
            model_name='mouvementpaie',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mouvementpaie',
            name='element_paie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='hr_payroll.elementpaie'),
        ),
        migrations.AddField(
            model_name='mutation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='hr_payroll.agent'),
        ),
        migrations.AddField(
            model_name='mutation',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mutation',
            name='destination_bureau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mutations_destination', to='hr_payroll.bureau'),
        ),
        migrations.AddField(
            model_name='mutation',
            name='origine_bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mutations_origine', to='hr_payroll.bureau'),
        ),
        migrations.AddField(
            model_name='participationformation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_formations', to='hr_payroll.agent'),
        ),
        migrations.AddField(
            model_name='participationformation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='hr_payroll.formation'),
        ),
        migrations.AddField(
            model_name='participationformation',
            name='inscrit_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='periodepaie',
            unique_together={('annee', 'mois')},
        ),
        migrations.AddField(
            model_name='mouvementpaie',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='hr_payroll.periodepaie'),
        ),
        migrations.AddField(
            model_name='historiquepaie',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='hr_payroll.periodepaie'),
        ),
        migrations.AddField(
            model_name='bulletinpaie',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='hr_payroll.periodepaie'),
        ),
        migrations.AddField(
            model_name='postebudgetaire',
            name='bureau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postes_budgetaires', to='hr_payroll.bureau'),
        ),
        migrations.AddField(
            model_name='postebudgetaire',
            name='grade_requis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='postes_budgetaires', to='hr_payroll.grade'),
        ),
        migrations.AddField(
            model_name='agent',
            name='poste_budgetaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='hr_payroll.postebudgetaire'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='poste_budgetaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='hr_payroll.postebudgetaire'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='hr_payroll.agent'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='grade_ancien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions_ancien', to='hr_payroll.grade'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='grade_nouveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions_nouveau', to='hr_payroll.grade'),
        ),
        migrations.AlterUniqueTogether(
            name='competenceagent',
            unique_together={('agent', 'competence')},
        ),
        migrations.AlterUniqueTogether(
            name='cotation',
            unique_together={('agent', 'annee', 'semestre', 'periode_evaluation')},
        ),
        migrations.AlterUniqueTogether(
            name='bureau',
            unique_together={('code', 'direction')},
        ),
        migrations.AlterUniqueTogether(
            name='participationformation',
            unique_together={('agent', 'formation')},
        ),
        migrations.AlterUniqueTogether(
            name='mouvementpaie',
            unique_together={('periode', 'agent', 'element_paie')},
        ),
        migrations.AlterUniqueTogether(
            name='bulletinpaie',
            unique_together={('periode', 'agent')},
        ),
    ]
